name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to JFrog Artifactory
        run: echo "${{ secrets.JF_TOKEN }}" | docker login ${{ secrets.JF_URL }} -u ${{ secrets.JF_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t elinaf.jfrog.io/test-local-basselm/oceaneering/actions-runner-linux:0.1.2-beta.14 .

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}

      - name: Configure JFrog CLI
        run: |
          jf c add my-server --url=${{ secrets.JF_URL }} --user=${{ secrets.JF_USERNAME }} --password=${{ secrets.JF_TOKEN }} --interactive=false
          jf c use my-server

      - name: Push Docker Image to JFrog Artifactory
        run: |
         jf docker push elinaf.jfrog.io/test-local-basselm/oceaneering/actions-runner-linux:0.1.2-beta.14
